-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/BlueSpiceBookshelf/maintenance/db/bs_books.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE bs_books (
  book_id SERIAL NOT NULL,
  book_namespace TEXT DEFAULT NULL,
  book_title TEXT DEFAULT NULL,
  book_type TEXT NOT NULL,
  PRIMARY KEY(book_id)
);

CREATE INDEX book_id_idx ON bs_books (book_id);
