-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/BlueSpiceBookshelf/maintenance/db/bs_book_meta.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE bs_book_meta (
  m_id SERIAL NOT NULL,
  m_book_id INT NOT NULL,
  m_key TEXT NOT NULL,
  m_value TEXT DEFAULT NULL,
  PRIMARY KEY(m_id)
);

CREATE INDEX m_id_idx ON bs_book_meta (m_id);
