-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/BlueSpiceBookshelf/maintenance/db/bs_book_chapters.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/bs_book_chapters (
  chapter_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  chapter_book_namespace BLOB NOT NULL,
  chapter_book_title BLOB NOT NULL,
  chapter_page_namespace BLOB,
  chapter_page_title BLOB,
  chapter_title BLOB,
  chapter_number BLOB NOT NULL,
  chapter_type BLOB NOT NULL
);

CREATE INDEX chapter_id_idx ON /*_*/bs_book_chapters (chapter_id);
