-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/BlueSpiceBookshelf/maintenance/db/bs_book_meta.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/bs_book_meta (
  m_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  m_book_id INTEGER UNSIGNED NOT NULL,
  m_key BLOB NOT NULL, m_value BLOB DEFAULT NULL
);

CREATE INDEX m_id_idx ON /*_*/bs_book_meta (m_id);
