-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: extensions/BlueSpiceBookshelf/maintenance/db/bs_book_chapters.patch.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TEMPORARY TABLE /*_*/__temp__bs_book_chapters AS
SELECT  chapter_id,  chapter_title,  chapter_number,  chapter_type
FROM  /*_*/bs_book_chapters;
DROP  TABLE  /*_*/bs_book_chapters;
CREATE TABLE  /*_*/bs_book_chapters (    chapter_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,    chapter_title BLOB DEFAULT NULL, chapter_number BLOB NOT NULL,    chapter_type BLOB NOT NULL, chapter_book_id INTEGER UNSIGNED NOT NULL,    chapter_namespace BLOB DEFAULT NULL,    chapter_name BLOB NOT NULL  );
INSERT INTO  /*_*/bs_book_chapters (    chapter_id, chapter_title, chapter_number,    chapter_type  )
SELECT  chapter_id,  chapter_title,  chapter_number,  chapter_type
FROM  /*_*/__temp__bs_book_chapters;
DROP  TABLE /*_*/__temp__bs_book_chapters;
CREATE INDEX chapter_id_idx ON  /*_*/bs_book_chapters (chapter_id);