-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/BlueSpiceBookshelf/maintenance/db/bs_books.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/bs_books (
  book_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  book_namespace BLOB DEFAULT NULL,
  book_title BLOB DEFAULT NULL,
  book_type BLOB NOT NULL
);

CREATE INDEX book_id_idx ON /*_*/bs_books (book_id);
