-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/BlueSpiceBookshelf/maintenance/db/bs_books.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/bs_books (
  book_id INT UNSIGNED AUTO_INCREMENT NOT NULL,
  book_namespace VARBINARY(255) DEFAULT NULL,
  book_title VARBINARY(255) DEFAULT NULL,
  book_type VARBINARY(255) NOT NULL,
  INDEX book_id_idx (book_id),
  PRIMARY KEY(book_id)
) /*$wgDBTableOptions*/;
