-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: extensions/BlueSpiceBookshelfDBFix/maintenance/db/bs_books.patch.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
ALTER TABLE  /*_*/bs_books
ADD  book_name VARBINARY(255) NOT NULL;