-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/BlueSpiceBookshelf/maintenance/db/bs_book_meta.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/bs_book_meta (
  m_id INT UNSIGNED AUTO_INCREMENT NOT NULL,
  m_book_id INT UNSIGNED NOT NULL,
  m_key VARBINARY(255) NOT NULL,
  m_value VARBINARY(255) DEFAULT NULL,
  INDEX m_id_idx (m_id),
  PRIMARY KEY(m_id)
) /*$wgDBTableOptions*/;
