-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/BlueSpiceBookshelf/maintenance/db/bs_book_chapters.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/bs_book_chapters (
  chapter_id INT UNSIGNED AUTO_INCREMENT NOT NULL,
  chapter_book_id INT UNSIGNED NOT NULL,
  chapter_namespace VARBINARY(255) DEFAULT NULL,
  chapter_title VARBINARY(255) DEFAULT NULL,
  chapter_name VARBINARY(255) NOT NULL,
  chapter_number VARBINARY(255) NOT NULL,
  chapter_type VARBINARY(255) NOT NULL,
  INDEX chapter_id_idx (chapter_id),
  PRIMARY KEY(chapter_id)
) /*$wgDBTableOptions*/;
