-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: extensions/BlueSpiceBookshelf/maintenance/db/bs_book_chapters.patch.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
ALTER TABLE  /*_*/bs_book_chapters
ADD  chapter_book_id INT UNSIGNED NOT NULL,
ADD  chapter_namespace VARBINARY(255) DEFAULT NULL,
ADD  chapter_name VARBINARY(255) NOT NULL,
DROP  chapter_book_namespace,
DROP  chapter_book_title,
DROP  chapter_page_namespace,
DROP  chapter_page_title,
CHANGE  chapter_title chapter_title VARBINARY(255) DEFAULT NULL;